#!/bin/bash

rm -fv Output.hs

cat <<EOF > Output.hs
-- This file is automatically generated. Do not change it by hand.

module Output where

import InterpreterPrelude

EOF

for f in ../out/*.hs
do
	echo $f
	echo -e "\n\n\n-- $f" >> Output.hs
	cat $f >> Output.hs
done
