name: Build atlas using Nix
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: cachix/install-nix-action@v12
      with:
        install_url: https://releases.nixos.org/nix/nix-2.5.1/install
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
    - run: |
        nix --version
        nix show-config
    - uses: cachix/cachix-action@v8
      with:
        name: lorenzleutgeb-public
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1.6.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}
    - name: Build 'atlas'
      id: atlas
      run: |
        PKG=atlas
        nix build .#$PKG --no-link --print-build-logs --json
        RESULT=$(nix path-info .#$PKG)
        echo "::set-output name=result::$RESULT"
        #RESULT_JACOCO=$(nix path-info .#packages.x86_64-linux.$PKG.jacoco)
        #echo "::set-output name=result-jacoco::$RESULT_JACOCO"
    - name: Build 'atlas-docker'
      id: atlas-docker
      run: |
        PKG=atlas-docker
        nix build .#$PKG --no-link --print-build-logs --json
        RESULT=$(nix path-info .#$PKG)
        docker load < $RESULT
        docker tag atlas:latest lorenzleutgeb/atlas:$GITHUB_SHA
        docker tag atlas:latest ghcr.io/lorenzleutgeb/atlas/atlas:$GITHUB_SHA
        echo "::set-output name=result::$RESULT"
    - name: Build 'atlas-shell-docker'
      id: atlas-shell-docker
      run: |
        PKG=atlas-shell-docker
        nix build .#$PKG --no-link --print-build-logs --json
        RESULT=$(nix path-info .#$PKG)
        docker load < $RESULT
        docker tag atlas-shell:latest lorenzleutgeb/atlas-shell:$GITHUB_SHA
        docker tag atlas-shell:latest ghcr.io/lorenzleutgeb/atlas/atlas-shell:$GITHUB_SHA
        echo "::set-output name=result::$RESULT"
    - name: Push Docker Images
      run: |
        docker push -q ghcr.io/lorenzleutgeb/atlas/atlas:$GITHUB_SHA
        docker push -q ghcr.io/lorenzleutgeb/atlas/atlas-shell:$GITHUB_SHA
   #- uses: codecov/codecov-action@v1
   #  with:
   #    files:  ${{ steps.atlas.outputs.result-jacoco }}
    - uses: actions/upload-artifact@v2
      with:
        name: atlas
        path: ${{ steps.atlas.outputs.result }}
    - uses: actions/upload-artifact@v2
      with:
        name: atlas-docker
        path: ${{ steps.atlas-docker.outputs.result }}
    - uses: actions/upload-artifact@v2
      with:
        name: atlas-shell-docker
        path: ${{ steps.atlas-shell-docker.outputs.result }}
